apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  namespace: chat
spec:
  replicas: 1 #pod scaling
  selector:
    matchLabels:
      app: chat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
        - name: chat
          image: kuo52033/chat-demo:production-1.7
          ports:
            - containerPort: 3005
          command: ["pm2-runtime"]
          args: ["start", "./pm2-processes/production.json", "--only", "chat-1"]
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 30
            timeoutSeconds: 15
            successThreshold: 1
            periodSeconds: 15

          volumeMounts:
            - name: log
              mountPath: /var/log/chat

      volumes:
        - name: log
          hostPath:
            path: /var/log/chat/production
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chat
spec:
  type: NodePort
  selector:
    app: chat
  ports:
    - protocol: TCP
      port: 3005 #service開放的
      targetPort: 3005 #pod開放的
      nodePort: 30000
