apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: chat
spec:
  replicas: 1 #pod scaling
  selector:
    matchLabels:
      app: redis
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chat
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379 #service開放的
      targetPort: 6379 #pod開放的
